name: bsteele_music_flutter
description: bsteele Music App in Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.12.0-236.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^2.0.13+1
  file_picker: ^2.1.4
  js: ^0.6.2
  logger: ^1.0.0-nullsafety.0
  package_info: ^0.4.3+2  # not nullable
  shared_preferences: ^0.5.12+4  # not nullable
  url_launcher: ^6.0.0-nullsafety.4
  universal_html: ^1.2.3  # not nullable
  intl: ^0.17.0-nullsafety.2
  path_provider: ^1.6.24  # not nullable
  flutter_markdown: ^0.5.1  # not nullable
  scrollable_positioned_list: ^0.1.7  # not nullable

  bsteeleMusicLib:
    path: ../bsteeleMusicLib/bsteele_music_lib


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.15
  build_runner: ^1.10.11  # not nullable
  build_web_compilers: ^2.16.0  # not nullable
  integration_test: ^1.0.1  # not nullable


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Bravura
      fonts:
        - asset: fonts/Bravura.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon.png"
